services:
    container-name:
        platform: linux/arm64
        build:
            context: .
            dockerfile: Dockerfile
        container_name: container-name
        ports:
            - "8500:8500"
        env_file:
            - .env.local # must create this .env.local file
        restart: unless-stopped
