services:
    container-name:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: container-name
        ports:
            - "8500:8500"
        env_file:
            - .env
        environment:
            - PYTHONPATH=/app
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8500/health')"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
